on: push
name: npm 
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        uses: actions/setup-node@v2
        with:
          args: install
          node-version: '12'
      - name: docker build
        uses: docker/setup-buildx-action@v1
        with:
          args: build -t nazeem358/first:git .
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker push
        uses: docker/build-push-action@v2
        with:
          args: push nazeem358/first:git
 
