on: push
name: npm 
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        uses: actions/setup-node@v1
        with:
          node-version: '12'
        run: npm install
      - name:  Build :latest
        run: docker build -t nazeem358/first:git .
      - name: docker login
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker push
        uses: actions-hub/docker@master
        with:
          args: push nazeem358/first:git
 
